# Generated by Django 5.2.5 on 2025-11-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
