# Generated by Django 5.2.7 on 2025-11-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
