# Generated by Django 5.2.7 on 2025-11-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_reviews_product_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Black', 'Black'), ('White', 'White'), ('Silver', 'Silver'), ('Gray', 'Gray'), ('Green', 'Green')], default='Black', max_length=50),
        ),
    ]
